### ISSUE TITLE
Failure on_load()

### ISSUE THREAD

**Issue by khoden** [raiguard/Factorio-RaiLuaLib#1]
Fail on save loading(

Current master with actual LTN Manager.

```
Error while running event RaiLuaLib::on_load()
__RaiLuaLib__/lualib/event.lua:141: bad argument #1 of 2 to 'pairs' (table expected, got nil)
stack traceback:
	[C]: in function 'pairs'
	__RaiLuaLib__/lualib/event.lua:141: in function <__RaiLuaLib__/lualib/event.lua:130>
```

**Comment by KhodeN** [comment]
Is there an actual working version of LTN Manager? I am using master, but not sure it is right way.

**Comment by raiguard** [comment]
LTN Manager is under heavy development so things may or may not work at the moment. That error looks like a result of my recent refactoring of my event module. I'll fix it after work and push so that you can continue to use it.

In the future, if anything is broken, it's likely that I already know about it. I'll only start accepting bug reports when I release it for alpha testing.

Thanks!

**Comment by raiguard** [comment]
So I took a look after finishing some Recipe Book updates, and this issue is not fixable. You have to disable LTN Manager, save your game, then re-add the mod to get it working again. I made some very significant architectural changes to the lualib and it needs a clean slate to work with.

**Comment by KhodeN** [comment]
It works, thank you!
